package candy.redpowerreborn.item;

import candy.redpowerreborn.RedPower;
import candy.redpowerreborn.block.RedPowerBlocks;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.ItemMeshDefinition;
import net.minecraft.client.renderer.RenderItem;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.item.EnumDyeColor;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemAxe;
import net.minecraft.item.ItemHoe;
import net.minecraft.item.ItemPickaxe;
import net.minecraft.item.ItemSeeds;
import net.minecraft.item.ItemSpade;
import net.minecraft.item.ItemStack;
import net.minecraft.item.ItemSword;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;

public class RedPowerItems {
	public static Item ATHAME;
	public static Item BATTERY;
	public static Item BLUE_ALLOY_INGOT;
	public static Item BLUE_DOPED_WAFER;
	public static Item BLULECTRIC_MOTOR;
	public static Item BRASS_INGOT;
	public static Item BRASS_GEAR;
	public static Item CANVAS;
	public static Item CANVAS_BAG;
	public static Item COPPER_COIL;
	public static Item COPPER_INGOT;
	public static Item COPPER_NUGGET;
	public static Item COPPER_WIRE;
	public static Item DIAMOND_DRAWPLATE;
	public static Item DIAMOND_HANDSAW;
	public static Item DIAMOND_SICKLE;
	public static Item EMERALD;
	public static Item EMERALD_AXE;
	public static Item EMERALD_HANDSAW;
	public static Item EMERALD_HOE;
	public static Item EMERALD_PICKAXE;
	public static Item EMERALD_SHOVEL;
	public static Item EMERALD_SICKLE;
	public static Item EMERALD_SWORD;
	public static Item FLAX_SEED;
	public static Item GOLD_SICKLE;
	public static Item INDIGO_DYE;
	public static Item IRON_HANDSAW;
	public static Item IRON_NUGGET;
	public static Item IRON_SICKLE;
	public static Item IRON_WIRE;
	public static Item LUMAR;
	public static Item NIKOLITE;
	public static Item PAINT_BRUSH;
	public static Item PAINT_BRUSH_WHITE;
	public static Item PAINT_BRUSH_BLACK;
	public static Item PAINT_BRUSH_ORANGE;
	public static Item PAINT_BRUSH_MAGENTA;
	public static Item PAINT_BRUSH_LIGHT_BLUE;
	public static Item PAINT_BRUSH_YELLOW;
	public static Item PAINT_BRUSH_LIME;
	public static Item PAINT_BRUSH_PINK;
	public static Item PAINT_BRUSH_GRAY;
	public static Item PAINT_BRUSH_LIGHT_GRAY;
	public static Item PAINT_BRUSH_CYAN;
	public static Item PAINT_BRUSH_PURPLE;
	public static Item paint_brush_blue;
	public static Item paint_brush_brown;
	public static Item paint_brush_green;
	public static Item paint_brush_red;
	public static Item paint_can;
	public static Item paint_can_white;
	public static Item paint_can_black;
	public static Item paint_can_orange;
	public static Item paint_can_magenta;
	public static Item paint_can_light_blue;
	public static Item paint_can_yellow;
	public static Item paint_can_lime;
	public static Item paint_can_pink;
	public static Item paint_can_gray;
	public static Item paint_can_light_gray;
	public static Item paint_can_cyan;
	public static Item paint_can_purple;
	public static Item paint_can_blue;
	public static Item paint_can_brown;
	public static Item paint_can_green;
	public static Item paint_can_red;
	public static Item plan;
	public static Item red_alloy_ingot;
	public static Item red_doped_wafer;
	public static Item ruby;
	public static Item ruby_axe;
	public static Item ruby_handsaw;
	public static Item ruby_hoe;
	public static Item ruby_pickaxe;
	public static Item ruby_shovel;
	public static Item ruby_sickle;
	public static Item ruby_sword;
	public static Item sapphire;
	public static Item sapphire_axe;
	public static Item sapphire_handsaw;
	public static Item sapphire_hoe;
	public static Item sapphire_pickaxe;
	public static Item sapphire_shovel;
	public static Item sapphire_sickle;
	public static Item sapphire_sword;
	public static Item screwdriver;
	public static Item seed_bag;
	public static Item silicon_boule;
	public static Item silicon_chip;
	public static Item silicon_wafer;
	public static Item silver_ingot;
	public static Item silver_nugget;
	public static Item sonic_screwdriver;
	public static Item stone_anode;
	public static Item stone_assembly;
	public static Item stone_bundle;
	public static Item stone_cathode;
	public static Item stone_pointer;
	public static Item stone_redwire;
	public static Item stone_sickle;
	public static Item stone_wafer;
	public static Item stone_wire;
	public static Item tainted_silicon_chip;
	public static Item tin_ingot;
	public static Item tin_nugget;
	public static Item tin_plate;
	public static Item voltmeter;
	public static Item wooden_sickle;
	public static Item wooden_sail;
	public static Item wooden_wind_turbine;
	public static Item wooden_windmill;
	public static Item wool_card;
	
	public static ToolMaterial EMERALD_TOOL_MATERIAL;
	public static ToolMaterial RUBY_TOOL_MATERIAL;
	public static ToolMaterial SAPPHIRE_TOOL_MATERIAL;

	public static void preInit(FMLPreInitializationEvent event) {
		
		//might have to register these after the emeralds but still before the tools
		EMERALD_TOOL_MATERIAL = EnumHelper.addToolMaterial("EMERALD", 2, 500, 8.0F, 3.0F, 8).setRepairItem(new ItemStack(EMERALD));//TODO check values later maybe
		RUBY_TOOL_MATERIAL = EnumHelper.addToolMaterial("RUBY", 2, 500, 8.0F, 3.0F, 8).setRepairItem(new ItemStack(ruby));
		SAPPHIRE_TOOL_MATERIAL = EnumHelper.addToolMaterial("SAPPHIRE", 2, 500, 8.0F, 3.0F, 8).setRepairItem(new ItemStack(sapphire));
		
		ATHAME = new ItemAthame().setUnlocalizedName(RedPower.MODID + "_athame").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(ATHAME, "athame");
		BATTERY = new ItemBattery().setUnlocalizedName(RedPower.MODID + "_battery").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(BATTERY, "battery");
		BLUE_ALLOY_INGOT = new Item().setUnlocalizedName(RedPower.MODID + "_ingotBlueAlloy").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(BLUE_ALLOY_INGOT, "blue_alloy_ingot");
		BLUE_DOPED_WAFER = new Item().setUnlocalizedName(RedPower.MODID + "_blueDopedWafer").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(BLUE_DOPED_WAFER, "blue_doped_wafer");
		BLULECTRIC_MOTOR = new Item().setUnlocalizedName(RedPower.MODID + "_blulectricMotor").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(BLULECTRIC_MOTOR, "blulectric_motor");
		BRASS_INGOT = new Item().setUnlocalizedName(RedPower.MODID + "_ingotBrass").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(BRASS_INGOT, "brass_ingot");
		BRASS_GEAR = new Item().setUnlocalizedName(RedPower.MODID + "_gearBrass").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(BRASS_GEAR, "brass_gear");
		CANVAS = new Item().setUnlocalizedName(RedPower.MODID + "_canvas").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(CANVAS, "canvas");
		CANVAS_BAG = new ItemCanvasBag().setUnlocalizedName(RedPower.MODID + "_canvasBag").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(CANVAS_BAG, "canvas_bag");
		COPPER_COIL = new Item().setUnlocalizedName(RedPower.MODID + "_coilCopper").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(COPPER_COIL, "copper_coil");
		COPPER_INGOT = new Item().setUnlocalizedName(RedPower.MODID + "_ingotCopper").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(COPPER_INGOT, "copper_ingot");
		COPPER_NUGGET = new Item().setUnlocalizedName(RedPower.MODID + "_nuggetCopper").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(COPPER_NUGGET, "copper_nugget");
		COPPER_WIRE = new Item().setUnlocalizedName(RedPower.MODID + "_wireCopper").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(COPPER_WIRE, "copper_wire");
		DIAMOND_DRAWPLATE = new ItemDrawplate(ToolMaterial.DIAMOND).setUnlocalizedName(RedPower.MODID + "_drawplateDiamond").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(DIAMOND_DRAWPLATE, "diamond_drawplate");
		DIAMOND_HANDSAW = new ItemHandsaw(ToolMaterial.DIAMOND).setUnlocalizedName(RedPower.MODID + "_handsawDiamond").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(DIAMOND_HANDSAW, "diamond_handsaw");
		DIAMOND_SICKLE = new ItemSickle(ToolMaterial.DIAMOND).setUnlocalizedName(RedPower.MODID + "_sickleDiamond").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(DIAMOND_SICKLE, "diamond_sickle");
		EMERALD = new Item().setUnlocalizedName(RedPower.MODID + "_emerald").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(EMERALD, "emerald");
		EMERALD_AXE = new ItemRedPowerAxe(EMERALD_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_axeEmerald").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(EMERALD_AXE, "emerald_axe");
		EMERALD_HANDSAW = new ItemHandsaw(EMERALD_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_handsawEmerald").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(EMERALD_HANDSAW, "emerald_handsaw");
		EMERALD_HOE = new ItemHoe(EMERALD_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_hoeEmerald").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(EMERALD_HOE, "emerald_hoe");
		EMERALD_PICKAXE = new ItemRedPowerPickaxe(EMERALD_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_pickaxeEmerald").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(EMERALD_PICKAXE, "emerald_pickaxe");
		EMERALD_SHOVEL = new ItemSpade(EMERALD_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_shovelEmerald").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(EMERALD_SHOVEL, "emerald_shovel");
		EMERALD_SICKLE = new ItemSickle(EMERALD_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_sickleEmerald").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(EMERALD_SICKLE, "emerald_sickle");
		EMERALD_SWORD = new ItemSword(EMERALD_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_swordEmerald").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(EMERALD_SWORD, "emerald_sword");
		FLAX_SEED = new ItemSeeds(RedPowerBlocks.flax, Blocks.FARMLAND).setUnlocalizedName(RedPower.MODID + "_seedFlax").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(FLAX_SEED, "flax_seed");
		GOLD_SICKLE = new ItemSickle(ToolMaterial.GOLD).setUnlocalizedName(RedPower.MODID + "_sickleGold").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(GOLD_SICKLE, "gold_sickle");
		INDIGO_DYE = new Item().setUnlocalizedName(RedPower.MODID + "_dye.indigo").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(INDIGO_DYE, "indigo_dye");
		IRON_HANDSAW = new ItemHandsaw(ToolMaterial.IRON).setUnlocalizedName(RedPower.MODID + "_handsawIron").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(IRON_HANDSAW, "iron_handsaw");
		IRON_NUGGET = new Item().setUnlocalizedName(RedPower.MODID + "_nuggetIron").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(IRON_NUGGET, "iron_nugget");
		IRON_SICKLE = new ItemSickle(ToolMaterial.IRON).setUnlocalizedName(RedPower.MODID + "_sickleIron").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(IRON_SICKLE, "iron_sickle");
		IRON_WIRE = new Item().setUnlocalizedName(RedPower.MODID + "_wireIron").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(IRON_WIRE, "iron_wire");
		LUMAR = new ItemLumar().setUnlocalizedName(RedPower.MODID + "_lumar").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(LUMAR, "lumar");
		NIKOLITE = new Item().setUnlocalizedName(RedPower.MODID + "_nikolite").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(NIKOLITE, "nikolite");
		PAINT_BRUSH = new Item().setUnlocalizedName(RedPower.MODID + "_paintBrush").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(PAINT_BRUSH, "paint_brush");
		PAINT_BRUSH_WHITE = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.white").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_WHITE, "paint_brush_white");
		PAINT_BRUSH_BLACK = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.black").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_BLACK, "paint_brush_black");
		PAINT_BRUSH_ORANGE = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.orange").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_ORANGE, "paint_brush_orange");
		PAINT_BRUSH_MAGENTA = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.magenta").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_MAGENTA, "paint_brush_magenta");
		PAINT_BRUSH_LIGHT_BLUE = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.lightBlue").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_LIGHT_BLUE, "paint_brush_light_blue");
		PAINT_BRUSH_YELLOW = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.yellow").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_YELLOW, "paint_brush_yellow");
		PAINT_BRUSH_LIME = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.lime").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_LIME, "paint_brush_lime");
		PAINT_BRUSH_PINK = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.pink").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_PINK, "paint_brush_pink");
		PAINT_BRUSH_GRAY = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.gray").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_GRAY, "paint_brush_gray");
		PAINT_BRUSH_LIGHT_GRAY = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.lightGray").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_LIGHT_GRAY, "paint_brush_light_gray");
		PAINT_BRUSH_CYAN = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.cyan").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_CYAN, "paint_brush_cyan");
		PAINT_BRUSH_PURPLE = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.purple").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(PAINT_BRUSH_PURPLE, "paint_brush_purple");
		paint_brush_blue = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.blue").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(paint_brush_blue, "paint_brush_blue");
		paint_brush_brown = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.brown").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(paint_brush_brown, "paint_brush_brown");
		paint_brush_green = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.green").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(paint_brush_green, "paint_brush_green");
		paint_brush_red = new ItemPaintBrush(EnumDyeColor.BLACK).setUnlocalizedName(RedPower.MODID + "_paintBrush.red").setCreativeTab(RedPower.tabRedPower);//maybe return an unlocalized name the way ItemDye does.
		GameRegistry.registerItem(paint_brush_red, "paint_brush_red");
		paint_can = new Item().setUnlocalizedName(RedPower.MODID + "_paintCan").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can, "paint_can");
		paint_can_white = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.white").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_white, "paint_can_white");
		paint_can_black = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.black").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_black, "paint_can_black");
		paint_can_orange = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.orange").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_orange, "paint_can_orange");
		paint_can_magenta = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.magenta").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_magenta, "paint_can_magenta");
		paint_can_light_blue = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.lightBlue").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_light_blue, "paint_can_light_blue");
		paint_can_yellow = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.yellow").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_yellow, "paint_can_yellow");
		paint_can_lime = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.lime").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_lime, "paint_can_lime");
		paint_can_pink = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.pink").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_pink, "paint_can_pink");
		paint_can_gray = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.gray").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_gray, "paint_can_gray");
		paint_can_light_gray = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.lightGray").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_light_gray, "paint_can_light_gray");
		paint_can_cyan = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.cyan").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_cyan, "paint_can_cyan");
		paint_can_purple = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.purple").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_purple, "paint_can_purple");
		paint_can_blue = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.blue").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_blue, "paint_can_blue");
		paint_can_brown = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.brown").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_brown, "paint_can_brown");
		paint_can_green = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.green").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_green, "paint_can_green");
		paint_can_red = new ItemPaintCan().setUnlocalizedName(RedPower.MODID + "_paintCan.red").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(paint_can_red, "paint_can_red");
		plan = new ItemPlan().setUnlocalizedName(RedPower.MODID + "_plan").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(plan, "plan");
		red_alloy_ingot = new Item().setUnlocalizedName(RedPower.MODID + "_ingotRedAlloy").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(red_alloy_ingot, "red_alloy_ingot");
		red_doped_wafer = new Item().setUnlocalizedName(RedPower.MODID + "_redDopedWafer").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(red_doped_wafer, "red_doped_wafer");
		ruby = new Item().setUnlocalizedName(RedPower.MODID + "_ruby").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(ruby, "ruby");
		ruby_axe = new ItemRedPowerAxe(RUBY_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_axeRuby").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(ruby_axe, "ruby_axe");
		ruby_handsaw = new ItemHandsaw(RUBY_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_handsawRuby").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(ruby_handsaw, "ruby_handsaw");
		ruby_hoe = new ItemHoe(RUBY_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_hoeRuby").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(ruby_hoe, "ruby_hoe");
		ruby_pickaxe = new ItemRedPowerPickaxe(RUBY_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_pickaxeRuby").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(ruby_pickaxe, "ruby_pickaxe");
		ruby_shovel = new ItemSpade(RUBY_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_shovelRuby").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(ruby_shovel, "ruby_shovel");
		ruby_sickle = new ItemSickle(RUBY_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_sickleRuby").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(ruby_sickle, "ruby_sickle");
		ruby_sword = new ItemSword(RUBY_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_swordRuby").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(ruby_sword, "ruby_sword");
		sapphire = new Item().setUnlocalizedName(RedPower.MODID + "_sapphire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(sapphire, "sapphire");
		sapphire_axe = new ItemRedPowerAxe(SAPPHIRE_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_axeSapphire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(sapphire_axe, "sapphire_axe");
		sapphire_handsaw = new ItemHandsaw(SAPPHIRE_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_handsawSapphire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(sapphire_handsaw, "sapphire_handsaw");
		sapphire_hoe = new ItemHoe(SAPPHIRE_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_hoeSapphire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(sapphire_hoe, "sapphire_hoe");
		sapphire_pickaxe = new ItemRedPowerPickaxe(SAPPHIRE_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_pickaxeSapphire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(sapphire_pickaxe, "sapphire_pickaxe");
		sapphire_shovel = new ItemSpade(SAPPHIRE_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_shovelSapphire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(sapphire_shovel, "sapphire_shovel");
		sapphire_sickle = new ItemSickle(SAPPHIRE_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_sickleSapphire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(sapphire_sickle, "sapphire_sickle");
		sapphire_sword = new ItemSword(RUBY_TOOL_MATERIAL).setUnlocalizedName(RedPower.MODID + "_swordSapphire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(sapphire_sword, "sapphire_sword");
		screwdriver = new Item/*Screwdriver*/().setUnlocalizedName(RedPower.MODID + "_screwdriver").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(screwdriver, "screwdriver");
		seed_bag = new Item/*SeedBag*/().setUnlocalizedName(RedPower.MODID + "_seedBag").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(seed_bag, "seed_bag");
		silicon_boule = new Item().setUnlocalizedName(RedPower.MODID + "_siliconBoule").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(silicon_boule, "silicon_boule");
		silicon_chip = new Item().setUnlocalizedName(RedPower.MODID + "_siliconChip").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(silicon_chip, "silicon_chip");
		silicon_wafer = new Item().setUnlocalizedName(RedPower.MODID + "_siliconWafer").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(silicon_wafer, "silicon_wafer");
		silver_ingot = new Item().setUnlocalizedName(RedPower.MODID + "_ingotSilver").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(silver_ingot, "silver_ingot");
		silver_nugget = new Item().setUnlocalizedName(RedPower.MODID + "_nuggetSilver").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(silver_nugget, "silver_nugget");
		sonic_screwdriver = new Item/*SonicScrewdriver*/().setUnlocalizedName(RedPower.MODID + "_sonicScrewdriver").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(sonic_screwdriver, "sonic_screwdriver");
		stone_anode = new Item().setUnlocalizedName(RedPower.MODID + "_stoneAnode").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(stone_anode, "stone_anode");
		stone_assembly = new Item().setUnlocalizedName(RedPower.MODID + "_stoneAssembly").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(stone_assembly, "stone_assembly");
		stone_bundle = new Item().setUnlocalizedName(RedPower.MODID + "_stoneBundle").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(stone_bundle, "stone_bundle");
		stone_cathode = new Item().setUnlocalizedName(RedPower.MODID + "_stoneCathode").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(stone_cathode, "stone_cathode");
		stone_pointer = new Item().setUnlocalizedName(RedPower.MODID + "_stonePointer").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(stone_pointer, "stone_pointer");
		stone_redwire = new Item().setUnlocalizedName(RedPower.MODID + "_stoneRedwire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(stone_redwire, "stone_redwire");
		stone_sickle = new ItemSickle(ToolMaterial.STONE).setUnlocalizedName(RedPower.MODID + "_sickleStone").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(stone_sickle, "stone_sickle");
		stone_wafer = new Item().setUnlocalizedName(RedPower.MODID + "_stoneWafer").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(stone_wafer, "stone_wafer");
		stone_wire = new Item().setUnlocalizedName(RedPower.MODID + "_stoneWire").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(stone_wire, "stone_wire");
		tainted_silicon_chip = new Item().setUnlocalizedName(RedPower.MODID + "_taintedSiliconChip").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(tainted_silicon_chip, "tainted_silicon_chip");
		tin_ingot = new Item().setUnlocalizedName(RedPower.MODID + "_ingotTin").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(tin_ingot, "tin_ingot");
		tin_nugget = new Item().setUnlocalizedName(RedPower.MODID + "_nuggetTin").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(tin_nugget, "tin_nugget");
		tin_plate = new Item().setUnlocalizedName(RedPower.MODID + "_tinPlate").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(tin_plate, "tin_plate");
		voltmeter = new ItemVoltmeter().setUnlocalizedName(RedPower.MODID + "_voltmeter").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(voltmeter, "voltmeter");
		wooden_sickle = new ItemSickle(ToolMaterial.WOOD).setUnlocalizedName(RedPower.MODID + "_sickleWooden").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(wooden_sickle, "wood_sickle");
		wooden_sail = new Item().setUnlocalizedName(RedPower.MODID + "_sail").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(wooden_sail, "wooden_sail");
		wooden_wind_turbine = new Item().setUnlocalizedName(RedPower.MODID + "_woodenWindTurbine").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(wooden_wind_turbine, "wooden_wind_turbine");
		wooden_windmill = new Item().setUnlocalizedName(RedPower.MODID + "_woodenWindmill").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(wooden_windmill, "wooden_windmill");
		wool_card = new ItemWoolCard().setUnlocalizedName(RedPower.MODID + "_woolCard").setCreativeTab(RedPower.tabRedPower);
		GameRegistry.registerItem(wool_card, "wool_card");
	}
	
	public static void init(FMLInitializationEvent event) {
		if (event.getSide() == Side.CLIENT) {
			RenderItem renderItem = Minecraft.getMinecraft().getRenderItem();
			
			renderItem.getItemModelMesher().register(ATHAME, 0, new ModelResourceLocation(RedPower.MODID + ":athame", "inventory"));
			renderItem.getItemModelMesher().register(BATTERY, 0, new ModelResourceLocation(RedPower.MODID + ":battery", "inventory"));
			renderItem.getItemModelMesher().register(BLUE_ALLOY_INGOT, 0, new ModelResourceLocation(RedPower.MODID + ":blue_alloy_ingot", "inventory"));
			renderItem.getItemModelMesher().register(BLUE_DOPED_WAFER, 0, new ModelResourceLocation(RedPower.MODID + ":blue_doped_wafer", "inventory"));
			renderItem.getItemModelMesher().register(BLULECTRIC_MOTOR, 0, new ModelResourceLocation(RedPower.MODID + ":blulectric_motor", "inventory"));
			renderItem.getItemModelMesher().register(BRASS_INGOT, 0, new ModelResourceLocation(RedPower.MODID + ":brass_ingot", "inventory"));
			renderItem.getItemModelMesher().register(BRASS_GEAR, 0, new ModelResourceLocation(RedPower.MODID + ":brass_gear", "inventory"));
			renderItem.getItemModelMesher().register(CANVAS, 0, new ModelResourceLocation(RedPower.MODID + ":canvas", "inventory"));
			Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(CANVAS_BAG, new ItemMeshDefinition() {
				public ModelResourceLocation getModelLocation(ItemStack stack) {
					return new ModelResourceLocation(RedPower.MODID + ":canvas_bag", "inventory");
				}
			});
			renderItem.getItemModelMesher().register(COPPER_COIL, 0, new ModelResourceLocation(RedPower.MODID + ":copper_coil", "inventory"));
			renderItem.getItemModelMesher().register(COPPER_INGOT, 0, new ModelResourceLocation(RedPower.MODID + ":copper_ingot", "inventory"));
			renderItem.getItemModelMesher().register(COPPER_NUGGET, 0, new ModelResourceLocation(RedPower.MODID + ":copper_nugget", "inventory"));
			renderItem.getItemModelMesher().register(COPPER_WIRE, 0, new ModelResourceLocation(RedPower.MODID + ":copper_wire", "inventory"));
			renderItem.getItemModelMesher().register(DIAMOND_DRAWPLATE, 0, new ModelResourceLocation(RedPower.MODID + ":diamond_drawplate", "inventory"));
			renderItem.getItemModelMesher().register(DIAMOND_HANDSAW, 0, new ModelResourceLocation(RedPower.MODID + ":diamond_handsaw", "inventory"));
			renderItem.getItemModelMesher().register(DIAMOND_SICKLE, 0, new ModelResourceLocation(RedPower.MODID + ":diamond_sickle", "inventory"));
			renderItem.getItemModelMesher().register(EMERALD, 0, new ModelResourceLocation(RedPower.MODID + ":emerald", "inventory"));
			renderItem.getItemModelMesher().register(EMERALD_AXE, 0, new ModelResourceLocation(RedPower.MODID + ":emerald_axe", "inventory"));
			renderItem.getItemModelMesher().register(EMERALD_HANDSAW, 0, new ModelResourceLocation(RedPower.MODID + ":emerald_handsaw", "inventory"));
			renderItem.getItemModelMesher().register(EMERALD_HOE, 0, new ModelResourceLocation(RedPower.MODID + ":emerald_hoe", "inventory"));
			renderItem.getItemModelMesher().register(EMERALD_PICKAXE, 0, new ModelResourceLocation(RedPower.MODID + ":emerald_pickaxe", "inventory"));
			renderItem.getItemModelMesher().register(EMERALD_SHOVEL, 0, new ModelResourceLocation(RedPower.MODID + ":emerald_shovel", "inventory"));
			renderItem.getItemModelMesher().register(EMERALD_SICKLE, 0, new ModelResourceLocation(RedPower.MODID + ":emerald_sickle", "inventory"));
			renderItem.getItemModelMesher().register(EMERALD_SWORD, 0, new ModelResourceLocation(RedPower.MODID + ":emerald_sword", "inventory"));
			renderItem.getItemModelMesher().register(FLAX_SEED, 0, new ModelResourceLocation(RedPower.MODID + ":flax_seed", "inventory"));
			renderItem.getItemModelMesher().register(GOLD_SICKLE, 0, new ModelResourceLocation(RedPower.MODID + ":gold_sickle", "inventory"));
			renderItem.getItemModelMesher().register(INDIGO_DYE, 0, new ModelResourceLocation(RedPower.MODID + ":indigo_dye", "inventory"));
			renderItem.getItemModelMesher().register(IRON_HANDSAW, 0, new ModelResourceLocation(RedPower.MODID + ":iron_handsaw", "inventory"));
			renderItem.getItemModelMesher().register(IRON_NUGGET, 0, new ModelResourceLocation(RedPower.MODID + ":iron_nugget", "inventory"));
			renderItem.getItemModelMesher().register(IRON_SICKLE, 0, new ModelResourceLocation(RedPower.MODID + ":iron_sickle", "inventory"));
			renderItem.getItemModelMesher().register(IRON_WIRE, 0, new ModelResourceLocation(RedPower.MODID + ":iron_wire", "inventory"));
			renderItem.getItemModelMesher().register(LUMAR, 0, new ModelResourceLocation(RedPower.MODID + ":lumar", "inventory"));//TODO  find out how to register the subitems of lumar
			renderItem.getItemModelMesher().register(NIKOLITE, 0, new ModelResourceLocation(RedPower.MODID + ":nikolite", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_WHITE, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_white", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_BLACK, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_black", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_ORANGE, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_orange", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_MAGENTA, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_magenta", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_LIGHT_BLUE, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_light_blue", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_YELLOW, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_yellow", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_LIME, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_lime", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_PINK, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_pink", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_GRAY, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_gray", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_LIGHT_GRAY, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_light_gray", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_CYAN, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_cyan", "inventory"));
			renderItem.getItemModelMesher().register(PAINT_BRUSH_PURPLE, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_purple", "inventory"));
			renderItem.getItemModelMesher().register(paint_brush_blue, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_blue", "inventory"));
			renderItem.getItemModelMesher().register(paint_brush_brown, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_brown", "inventory"));
			renderItem.getItemModelMesher().register(paint_brush_green, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_green", "inventory"));
			renderItem.getItemModelMesher().register(paint_brush_red, 0, new ModelResourceLocation(RedPower.MODID + ":paint_brush_red", "inventory"));
			renderItem.getItemModelMesher().register(paint_can, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_white, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_white", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_black, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_black", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_orange, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_orange", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_magenta, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_magenta", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_light_blue, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_light_blue", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_yellow, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_yellow", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_lime, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_lime", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_pink, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_pink", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_gray, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_gray", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_light_gray, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_light_gray", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_cyan, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_cyan", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_purple, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_purple", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_blue, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_blue", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_brown, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_brown", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_green, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_green", "inventory"));
			renderItem.getItemModelMesher().register(paint_can_red, 0, new ModelResourceLocation(RedPower.MODID + ":paint_can_red", "inventory"));
			renderItem.getItemModelMesher().register(plan, 0, new ModelResourceLocation(RedPower.MODID + ":plan", "inventory"));
			renderItem.getItemModelMesher().register(red_alloy_ingot, 0, new ModelResourceLocation(RedPower.MODID + ":red_alloy_ingot", "inventory"));
			renderItem.getItemModelMesher().register(red_doped_wafer, 0, new ModelResourceLocation(RedPower.MODID + ":red_doped_wafer", "inventory"));
			renderItem.getItemModelMesher().register(ruby, 0, new ModelResourceLocation(RedPower.MODID + ":ruby", "inventory"));
			renderItem.getItemModelMesher().register(ruby_axe, 0, new ModelResourceLocation(RedPower.MODID + ":ruby_axe", "inventory"));
			renderItem.getItemModelMesher().register(ruby_handsaw, 0, new ModelResourceLocation(RedPower.MODID + ":ruby_handsaw", "inventory"));
			renderItem.getItemModelMesher().register(ruby_hoe, 0, new ModelResourceLocation(RedPower.MODID + ":ruby_hoe", "inventory"));
			renderItem.getItemModelMesher().register(ruby_pickaxe, 0, new ModelResourceLocation(RedPower.MODID + ":ruby_pickaxe", "inventory"));
			renderItem.getItemModelMesher().register(ruby_shovel, 0, new ModelResourceLocation(RedPower.MODID + ":ruby_shovel", "inventory"));
			renderItem.getItemModelMesher().register(ruby_sickle, 0, new ModelResourceLocation(RedPower.MODID + ":ruby_sickle", "inventory"));
			renderItem.getItemModelMesher().register(ruby_sword, 0, new ModelResourceLocation(RedPower.MODID + ":ruby_sword", "inventory"));
			renderItem.getItemModelMesher().register(sapphire, 0, new ModelResourceLocation(RedPower.MODID + ":sapphire", "inventory"));
			renderItem.getItemModelMesher().register(sapphire_axe, 0, new ModelResourceLocation(RedPower.MODID + ":sapphire_axe", "inventory"));
			renderItem.getItemModelMesher().register(sapphire_handsaw, 0, new ModelResourceLocation(RedPower.MODID + ":sapphire_handsaw", "inventory"));
			renderItem.getItemModelMesher().register(sapphire_hoe, 0, new ModelResourceLocation(RedPower.MODID + ":sapphire_hoe", "inventory"));
			renderItem.getItemModelMesher().register(sapphire_pickaxe, 0, new ModelResourceLocation(RedPower.MODID + ":sapphire_pickaxe", "inventory"));
			renderItem.getItemModelMesher().register(sapphire_shovel, 0, new ModelResourceLocation(RedPower.MODID + ":sapphire_shovel", "inventory"));
			renderItem.getItemModelMesher().register(sapphire_sickle, 0, new ModelResourceLocation(RedPower.MODID + ":sapphire_sickle", "inventory"));
			renderItem.getItemModelMesher().register(sapphire_sword, 0, new ModelResourceLocation(RedPower.MODID + ":sapphire_sword", "inventory"));
			renderItem.getItemModelMesher().register(screwdriver, 0, new ModelResourceLocation(RedPower.MODID + ":screwdriver", "inventory"));
			renderItem.getItemModelMesher().register(seed_bag, 0, new ModelResourceLocation(RedPower.MODID + ":seed_bag", "inventory"));
			renderItem.getItemModelMesher().register(silicon_boule, 0, new ModelResourceLocation(RedPower.MODID + ":silicon_boule", "inventory"));
			renderItem.getItemModelMesher().register(silicon_chip, 0, new ModelResourceLocation(RedPower.MODID + ":silicon_chip", "inventory"));
			renderItem.getItemModelMesher().register(silicon_wafer, 0, new ModelResourceLocation(RedPower.MODID + ":silicon_wafer", "inventory"));
			renderItem.getItemModelMesher().register(silver_ingot, 0, new ModelResourceLocation(RedPower.MODID + ":silver_ingot", "inventory"));
			renderItem.getItemModelMesher().register(silver_nugget, 0, new ModelResourceLocation(RedPower.MODID + ":silver_nugget", "inventory"));
			renderItem.getItemModelMesher().register(sonic_screwdriver, 0, new ModelResourceLocation(RedPower.MODID + ":sonic_screwdriver", "inventory"));
			renderItem.getItemModelMesher().register(stone_anode, 0, new ModelResourceLocation(RedPower.MODID + ":stone_anode", "inventory"));
			renderItem.getItemModelMesher().register(stone_assembly, 0, new ModelResourceLocation(RedPower.MODID + ":stone_assembly", "inventory"));
			renderItem.getItemModelMesher().register(stone_bundle, 0, new ModelResourceLocation(RedPower.MODID + ":stone_bundle", "inventory"));
			renderItem.getItemModelMesher().register(stone_cathode, 0, new ModelResourceLocation(RedPower.MODID + ":stone_cathode", "inventory"));
			renderItem.getItemModelMesher().register(stone_pointer, 0, new ModelResourceLocation(RedPower.MODID + ":stone_pointer", "inventory"));
			renderItem.getItemModelMesher().register(stone_redwire, 0, new ModelResourceLocation(RedPower.MODID + ":stone_redwire", "inventory"));
			renderItem.getItemModelMesher().register(stone_sickle, 0, new ModelResourceLocation(RedPower.MODID + ":stone_sickle", "inventory"));
			renderItem.getItemModelMesher().register(stone_wafer, 0, new ModelResourceLocation(RedPower.MODID + ":stone_wafer", "inventory"));
			renderItem.getItemModelMesher().register(stone_wire, 0, new ModelResourceLocation(RedPower.MODID + ":stone_wire", "inventory"));
			renderItem.getItemModelMesher().register(tainted_silicon_chip, 0, new ModelResourceLocation(RedPower.MODID + ":tainted_silicon_chip", "inventory"));
			renderItem.getItemModelMesher().register(tin_ingot, 0, new ModelResourceLocation(RedPower.MODID + ":tin_ingot", "inventory"));
			renderItem.getItemModelMesher().register(tin_nugget, 0, new ModelResourceLocation(RedPower.MODID + ":tin_nugget", "inventory"));
			renderItem.getItemModelMesher().register(tin_plate, 0, new ModelResourceLocation(RedPower.MODID + ":tin_plate", "inventory"));
			renderItem.getItemModelMesher().register(voltmeter, 0, new ModelResourceLocation(RedPower.MODID + ":voltmeter", "inventory"));
			renderItem.getItemModelMesher().register(wooden_sickle, 0, new ModelResourceLocation(RedPower.MODID + ":wood_sickle", "inventory"));
			renderItem.getItemModelMesher().register(wooden_sail, 0, new ModelResourceLocation(RedPower.MODID + ":wooden_sail", "inventory"));
			renderItem.getItemModelMesher().register(wooden_wind_turbine, 0, new ModelResourceLocation(RedPower.MODID + ":wooden_wind_turbine", "inventory"));
			renderItem.getItemModelMesher().register(wooden_windmill, 0, new ModelResourceLocation(RedPower.MODID + ":wooden_windmill", "inventory"));
			renderItem.getItemModelMesher().register(wool_card, 0, new ModelResourceLocation(RedPower.MODID + ":wool_card", "inventory"));
		}
	}
}